### PR TITLE
Package rename to io.cdap and upgrade to 6.0.0

### PR DESCRIPTION
**Pull request by anew**
title says it all. Two commits best reviewed independenty:
- renaming
- adapting to 6.0.0 CDAP changes

### CODE REVIEW

**Comment by anwar6953** [comment]
I'm curious - Does compilation fail if you don't do the second commit?

**Comment by anew** [comment]
checkstyle fails with some imports out of order. Other than that, compilation went through but tests failed, because flows and streams do not exist any more, so, for example, ProgramType.valueOf("FLOW") throws exception.

**Comment by anew** [comment]
Actually compilation also failed because some APIs had changed, most notably, the AuthorizationContext implements Admin and SecureStore, which have methods added and/or renamed.

**Comment by anwar6953** [comment]
Got it. We should've done second commit a while back when we did the stream/flow removal, but missed it. Thanks for including it now.

**Review by anwar6953 — APPROVED** [review]

**Comment by anew** [comment]
Right :) Thanks, so I will not squash the commits but keep'em separate.

**Pull request merged**
